# Generated by Django 4.0.6 on 2022-07-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cvv', models.CharField(max_length=3)),
                ('balance', models.FloatField()),
                ('status', models.CharField(choices=[('not activated', 'Неактивована'), ('activated', 'Активована'), ('overdue', 'Прострочена')], default='not activated', max_length=15)),
                ('balance_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='main_app.balance')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.series')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_card', to='main_app.card'),
        ),
    ]
