# Generated by Django 4.0.6 on 2022-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='balance_mod',
        ),
        migrations.AlterField(
            model_name='balance',
            name='name',
            field=models.CharField(blank=True, default='Платіж', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
